"""spot model changed

Revision ID: 66a34b9a583d
Revises: 6b70fea6ac60
Create Date: 2025-09-22 15:55:14.322007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a34b9a583d'
down_revision = '6b70fea6ac60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###
