"""made booking.hours nullable

Revision ID: 6b70fea6ac60
Revises: a3bd0388eae0
Create Date: 2025-09-21 15:38:40.052979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b70fea6ac60'
down_revision = 'a3bd0388eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('slot',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('slot',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
