"""Added fields

Revision ID: 75c3f513ca64
Revises: 66a34b9a583d
Create Date: 2025-10-11 21:36:54.980020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c3f513ca64'
down_revision = '66a34b9a583d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('booked')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('reviewed')
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
