"""Added Booking Model

Revision ID: a3bd0388eae0
Revises: b1b90be8a6aa
Create Date: 2025-09-21 14:03:31.207798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bd0388eae0'
down_revision = 'b1b90be8a6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('slot')

    # ### end Alembic commands ###
