"""Added Booking Model

Revision ID: b1b90be8a6aa
Revises: e69e9f7414b4
Create Date: 2025-09-21 13:30:45.144174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b90be8a6aa'
down_revision = 'e69e9f7414b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
