"""Add spot model

Revision ID: cbec791bf09e
Revises: 9b531f45fee1
Create Date: 2025-08-28 18:52:26.408351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbec791bf09e'
down_revision = '9b531f45fee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('slot_from', sa.Time(), nullable=False),
    sa.Column('slot_till', sa.Time(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot')
    # ### end Alembic commands ###
